name: Docker Build
on: [push]
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          docker build . --file Dockerfile -t docker.pkg.github.com/mokhan/asdfjkl/asdfjkl:latest
          docker login docker.pkg.github.com -u mokhan -p ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/mokhan/asdfjkl/asdfjkl:latest
